messange:
  1: "------------------------------"
  2: "------Wyczyszczono chat-------"
  3: "--------gotowe----------------"
  4: "------------------------------"

  permisja: "§aNie masz permisji"
  uzycie: "Urzyj /chat clear!"